### PR TITLE
enhancement for console at recording conversations

### PR DESCRIPTION
**Pull request by petuscov**
Now previous messages sended are accesible with arrow keys (up/down) terminal alike.

### CODE REVIEW

**Comment by petuscov** [comment]
Humm... That is strange, i have to check it.

**Comment by petuscov** [comment]
Well, #save command works fine for me in fbdirect mode, but #exit command doesn't, i have to fix it. 
However, if for Watson there are errors, maybe is an enhancement too big to be done...

**Comment by petuscov** [comment]
With this last commit '#exit' command should work fine. Watson problems could be fixed or not, i dont know.
Btw Florian, Codeship output is nto visible to me as contributor, sry, i forgot to answer you in testmybot pull request.

**Comment by codeforequity-at** [comment]
I don't have a clue how to automatically publish the Codeship build output here - I think in near future there will be a Botium developer channel on Slack for this.

By the way, you should always run "npm run build" before pusing - that's exactly the same as the Codeship build does ... so if "npm run build" succeeds locally, Codeship build will succeed as well (in most cases).

**Comment by codeforequity-at** [comment]
Build 0.0.12 is available now, including your fixes. 
Thanks for the contribution!

**Pull request merged**
